# fly.toml app configuration file generated for fastify-recipes-api on 2024-04-23T09:45:03-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastify-recipes-api'
primary_region = 'sea'

[build]

[deploy]
  release_command = "npx knex migrate:latest --env production"

[env]
  PORT = "3000"
  DATABASE_ENVIRONMENT = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
