GET http://localhost:3003/recipes

###

GET http://localhost:3003/recipes?filter=salad

###

GET http://localhost:3003/recipes/d19be4c4-d059-4c86-993b-76a92e9e16bf

###

POST http://localhost:3003/recipes
Content-Type: application/json

{
	"name": "Caesar salad",
	"ingredients": "lettuce, croutons",
	"time": 5,
	"steps": "Put everything in a bowl"
}

###

PUT http://localhost:3003/recipes/d19be4c4-d059-4c86-993b-76a92e9e16bf
Content-Type: application/json

{
	"name": "Caesar salad v2",
	"ingredients": "lettuce, croutons, parmesan, olive oil",
	"time": 5,
	"steps": "Put everything in a bowl"
}

###

DELETE http://localhost:3003/recipes/afef2d6a-7e2d-422b-875e-b46a336ae900
